### ISSUE TITLE
Tamanho do campo txt igual a zero

### ISSUE THREAD

**Issue by gustavoamorimqueiroz** [samuelrochaoliveira/SPEDBr#24]
Olá. O tamanho do campo Txt do registro 460 do bloco0 está com o tamanho zero. Este campo informa a observação de documentos fiscais, portanto não pode ser zerado.

**Comment by samuelrochaoliveira** [comment]
@gustavoamorimqueiroz fiz a correção no commit https://github.com/samuelrochaoliveira/SPEDBr/commit/0a2017f903c9e5b6033deac04f96847028bceb38.
