### ISSUE TITLE
Correcao RegistroC420 SpedFiscal

### ISSUE THREAD

**Issue by victorcarlosgf** [samuelrochaoliveira/SPEDBr#25]
Existe um erro de escrita do registro C420 do SPED Fiscal, o campo Nr_Tot está sendo escrito com zeros quando não passamos um valor para a variável, porém em alguns casos como totalizadores(Can-T) esse campo deve ficar vazio(branco).

**Comment by samuelrochaoliveira** [comment]
@victorcarlosgf fiz a correção.

Veja como ficou a geração da linha agora.

![image](https://user-images.githubusercontent.com/15462690/29014346-f39aec02-7b1e-11e7-85ce-ccf1570bcfa4.png)
