### ISSUE TITLE
Correção Registro Encerramento de Bloco Sped Contribuicoes

### ISSUE THREAD

**Issue by victorcarlosgf** [samuelrochaoliveira/SPEDBr#27]
O registro de encerramento de bloco(990), dos blocos 0, 1, A, C, F, I, M e P do sped Contribuicoes possui um erro no campo 'tamanho', está com o valor 0 no entanto o correto seria o int.MaxValue;

**Comment by samuelrochaoliveira** [comment]
Correção feita no commit https://github.com/samuelrochaoliveira/SPEDBr/commit/b8dc00cebf93ac40ce6c913c38adf887224a61e8.
