### ISSUE TITLE
speed para ct-e OS

### ISSUE THREAD

**Issue by robertorp** [samuelrochaoliveira/SPEDBr#33]
speed para ct-e os, poderia me informar como funcionária ? Digo nem sei se existe o mesmo, estou com alguns clientes que são do regime normal, e me caiu esse problema para resolver, ai queria saber o caminho das pedras hehe, qual registro seria o especifico para o ct-e os ou se existe tal coisa ne

Obrigado.

**Comment by samuelrochaoliveira** [comment]
Fala @robertorp, na paz?
O CTeOS (67) ja está disponível no SPED ICMS/IPI e deverá ser lançado no registro D100 como se fosse CTe (57), agora... na EFD Contribuições, não vi atualização no layout ainda, vou consultar e te aviso.

A regra geral é, se é documento fiscal deve aparecer no Sped, a menos que a empresa seja do Simples Nacional ou não obrigada.

Abraços.

**Comment by robertorp** [comment]
@samuelrochaoliveira , você presta algum tipo de treinamento para speed? Digo não algo profundo detalhadamente, mas sim entender todo o processo em volta do speed como funciona.

**Comment by samuelrochaoliveira** [comment]
Sim, atualmente presto assessoria e consultoria em GO, já fiz trabalhos em SP e BA nos segmentos de construçao, hotelaria e varejo.

Me encaminhe um e-mail, poderemos conversar melhor.

Abraços.

**Comment by robertorp** [comment]
ok, obrigado.
